//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense_Tracker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNganSach
    {
        public int MaChiTietNganSach { get; set; }
        public int MaNganSach { get; set; }
        public string MaDM { get; set; }
        public decimal SoTienKeHoach { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual NganSach NganSach { get; set; }
    }
}
