//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense_Tracker.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EXPENSE_TRACKER_DB_Entities : DbContext
    {
        public EXPENSE_TRACKER_DB_Entities()
            : base("name=EXPENSE_TRACKER_DB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietNganSach> ChiTietNganSach { get; set; }
        public virtual DbSet<ChiTietPhieu> ChiTietPhieu { get; set; }
        public virtual DbSet<DanhMuc> DanhMuc { get; set; }
        public virtual DbSet<NganSach> NganSach { get; set; }
        public virtual DbSet<NguoiDung> NguoiDung { get; set; }
        public virtual DbSet<PhieuThuChi> PhieuThuChi { get; set; }
        public virtual DbSet<TaiKhoanQuy> TaiKhoanQuy { get; set; }
        public virtual DbSet<VaiTro> VaiTro { get; set; }
    
        public virtual ObjectResult<sp_BaoCaoChiTietTheoThoiGian_Result> sp_BaoCaoChiTietTheoThoiGian(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaoCaoChiTietTheoThoiGian_Result>("sp_BaoCaoChiTietTheoThoiGian", tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<sp_BaoCaoThuChiTheoThangChiTiet_Result> sp_BaoCaoThuChiTheoThangChiTiet(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaoCaoThuChiTheoThangChiTiet_Result>("sp_BaoCaoThuChiTheoThangChiTiet", thangParameter, namParameter);
        }
    
        public virtual ObjectResult<string> sp_Call_ChuyenSoTienThanhChu(Nullable<decimal> amount)
        {
            var amountParameter = amount.HasValue ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Call_ChuyenSoTienThanhChu", amountParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> sp_Call_KiemTraQuyDuTien(string maQuy, Nullable<decimal> soTienChi)
        {
            var maQuyParameter = maQuy != null ?
                new ObjectParameter("MaQuy", maQuy) :
                new ObjectParameter("MaQuy", typeof(string));
    
            var soTienChiParameter = soTienChi.HasValue ?
                new ObjectParameter("SoTienChi", soTienChi) :
                new ObjectParameter("SoTienChi", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("sp_Call_KiemTraQuyDuTien", maQuyParameter, soTienChiParameter);
        }
    
        public virtual ObjectResult<string> sp_Call_LayHoTenNguoiLap(Nullable<int> maND)
        {
            var maNDParameter = maND.HasValue ?
                new ObjectParameter("MaND", maND) :
                new ObjectParameter("MaND", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Call_LayHoTenNguoiLap", maNDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_Call_LayTongSoDu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_Call_LayTongSoDu");
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_Call_TinhSoDuCuoiKy(string maQuy, Nullable<System.DateTime> ngay)
        {
            var maQuyParameter = maQuy != null ?
                new ObjectParameter("MaQuy", maQuy) :
                new ObjectParameter("MaQuy", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_Call_TinhSoDuCuoiKy", maQuyParameter, ngayParameter);
        }
    
        public virtual ObjectResult<sp_SaoKeTaiKhoanQuy_Result> sp_SaoKeTaiKhoanQuy(string maQuy, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var maQuyParameter = maQuy != null ?
                new ObjectParameter("MaQuy", maQuy) :
                new ObjectParameter("MaQuy", typeof(string));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SaoKeTaiKhoanQuy_Result>("sp_SaoKeTaiKhoanQuy", maQuyParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual int sp_ThemPhieuThuChiTuDong(string soPhieu, Nullable<System.DateTime> ngayLap, string loaiPhieu, string nguoiNopNhan, string lyDoChung, Nullable<decimal> tongTien, string maQuy, Nullable<int> nguoiLapPhieu)
        {
            var soPhieuParameter = soPhieu != null ?
                new ObjectParameter("SoPhieu", soPhieu) :
                new ObjectParameter("SoPhieu", typeof(string));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            var loaiPhieuParameter = loaiPhieu != null ?
                new ObjectParameter("LoaiPhieu", loaiPhieu) :
                new ObjectParameter("LoaiPhieu", typeof(string));
    
            var nguoiNopNhanParameter = nguoiNopNhan != null ?
                new ObjectParameter("NguoiNopNhan", nguoiNopNhan) :
                new ObjectParameter("NguoiNopNhan", typeof(string));
    
            var lyDoChungParameter = lyDoChung != null ?
                new ObjectParameter("LyDoChung", lyDoChung) :
                new ObjectParameter("LyDoChung", typeof(string));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(decimal));
    
            var maQuyParameter = maQuy != null ?
                new ObjectParameter("MaQuy", maQuy) :
                new ObjectParameter("MaQuy", typeof(string));
    
            var nguoiLapPhieuParameter = nguoiLapPhieu.HasValue ?
                new ObjectParameter("NguoiLapPhieu", nguoiLapPhieu) :
                new ObjectParameter("NguoiLapPhieu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemPhieuThuChiTuDong", soPhieuParameter, ngayLapParameter, loaiPhieuParameter, nguoiNopNhanParameter, lyDoChungParameter, tongTienParameter, maQuyParameter, nguoiLapPhieuParameter);
        }
    
        public virtual ObjectResult<sp_ThongKeThuChiThang_Result> sp_ThongKeThuChiThang(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeThuChiThang_Result>("sp_ThongKeThuChiThang", thangParameter, namParameter);
        }
    
        public virtual ObjectResult<sp_TongHopChiTieuTheoDanhMuc_Result> sp_TongHopChiTieuTheoDanhMuc(string loaiDM, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var loaiDMParameter = loaiDM != null ?
                new ObjectParameter("LoaiDM", loaiDM) :
                new ObjectParameter("LoaiDM", typeof(string));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TongHopChiTieuTheoDanhMuc_Result>("sp_TongHopChiTieuTheoDanhMuc", loaiDMParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<sp_XacThucTaiKhoan_Result> sp_XacThucTaiKhoan(string tenDangNhap, string matKhauHash)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauHashParameter = matKhauHash != null ?
                new ObjectParameter("MatKhauHash", matKhauHash) :
                new ObjectParameter("MatKhauHash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XacThucTaiKhoan_Result>("sp_XacThucTaiKhoan", tenDangNhapParameter, matKhauHashParameter);
        }
    }
}
