//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense_Tracker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NganSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NganSach()
        {
            this.ChiTietNganSach = new HashSet<ChiTietNganSach>();
        }
    
        public int MaNganSach { get; set; }
        public int MaND { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public decimal TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNganSach> ChiTietNganSach { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
