//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense_Tracker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanQuy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoanQuy()
        {
            this.PhieuThuChi = new HashSet<PhieuThuChi>();
        }
    
        public string MaQuy { get; set; }
        public string TenQuy { get; set; }
        public decimal SoDuBanDau { get; set; }
        public decimal SoDuHienTai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuThuChi> PhieuThuChi { get; set; }
    }
}
